### ISSUE TITLE
请问古怪的字是怎么处理的？

### ISSUE THREAD

**Issue by StevenLOL** [jackeyGao/chinese-poetry#2]
我知道古诗里有很多古怪的字，在现在字库里没有，想知道这部分是怎么处理的。

**Comment by jackeyGao** [comment]
你是在什么需求下的问题？  转换到简体吗？

**Comment by StevenLOL** [comment]
嗯 已经知道了 谢谢

**Comment by animalize** [comment]
我只接触了唐诗部分，说说我看到的。
生僻字是以拆字的方式存在的，比如：`千里起足下，豐年繫鎡{釒基}。`、`敢憚榱{木欒}蠹，深藏柱石傾。`
所有字的code point都<=0xFFFF，在技术上很好处理。
