### ISSUE TITLE
关于词牌名信息

### ISSUE THREAD

**Issue by xinyuwufei** [jackeyGao/chinese-poetry#3]
对于宋词，请问有数据相应的词牌名信息或者分类嘛？
:‑)

**Comment by xinyuwufei** [comment]
不好意思，看错了。把宋诗看成宋词了...
请问 宋词 的资源吗？

**Comment by jackeyGao** [comment]
@xinyuwufei  暂未找到可采集的源。

**Comment by xinyuwufei** [comment]
好的，非常感谢你repo提供的资源！
我看宋词的爬取资源有很多是从 ‘古诗文’网上挖取的
不过可能这个源的可靠性不非常高
