### ISSUE TITLE
想知道数据来源，使用的话是否会侵权？

### ISSUE THREAD

**Issue by animalize** [jackeyGao/chinese-poetry#5]
写了个安卓的《离线全唐诗》，打算免费、开源：https://github.com/animalize/QuanTangshi
用的您这个数据，效果还不错。

就是想知道，如果我分发程序，是否会侵权？

**Comment by jackeyGao** [comment]
唐诗https://zh.wikipedia.org/zh-cn/%E5%85%A8%E5%94%90%E8%A9%A9   和  宋诗https://zh.wikipedia.org/wiki/%E5%85%A8%E5%AE%8B%E8%A9%A9  宋词https://zh.wikipedia.org/wiki/%E5%85%A8%E5%AE%8B%E8%A9%9E   按照我国的版权法， 古代的诗人的作品在现代版权也无效了。   对于此仓库数据， 我整理后也不知道用哪个license合适， 但是初衷是让更多的人使用， 所以你可以自由使用分发。   ：）

**Comment by animalize** [comment]
好的。已看到MIT协议，我把这个issue关了吧。
