### ISSUE TITLE
poet.tang.49000.json里的诗包括596个“YY”

### ISSUE THREAD

**Issue by animalize** [jackeyGao/chinese-poetry#7]
是这个文件  
https://github.com/jackeyGao/chinese-poetry/blob/master/json/poet.tang.49000.json

其中596首诗包含`YY`这两个字符，请问这是什么含义啊？   
例： 

"paragraphs": [  
"飄飄且在三峰下，秋風往往堪霑灑。",  
"腸斷憶仙宮，朦朧煙霧中。",  
"`YY`思夢時時睡，不語長如醉。",  
"早晚是歸期，蒼穹知不知。"    
], 

别的唐诗文件里没有`YY`，只有这个有。

**Comment by jackeyGao** [comment]
@animalize  我看了一下， 这些应该是脏数据。  我试着去找到源数据的位置， 但是源数据网站已经打不开了。有一种可能是我调试的时候加进去的（事实上爬这些数据中间中断并调试了好多次）。 YY字符只存在这个文件， 后面有空我把这个文件的YY替换掉.    感谢发现问题！ ：）

**Comment by animalize** [comment]
对了，唐诗里还有192首，paragraphs里并没有实质内容，比如这个：

{  
"strains": ["？？？？？？。"  ], 
"author": "麗天和尚",   
"paragraphs": ["-1422-。"],   
"title": ""  
}, 

我的程序里会保留这些空诗，这样编号就能和您的数据保持一致了。

**Comment by jackeyGao** [comment]
@animalize 有些可能收录的时候就缺失， 还有就是生僻字。

**Comment by animalize** [comment]
把这个关了吧
