### ISSUE TITLE
some most common ones are not collected?

### ISSUE THREAD

**Issue by oldyellowcat** [jackeyGao/chinese-poetry#9]
21050首词 --- 但是很多口水词，例如明月几时有 (明月幾時有)。。没有收录？还是我没找对？
 也没找到床前明月光 。。。

**Comment by jackeyGao** [comment]
宋词是简体中文字体入库， 和唐诗的json文件不同.
`select * from ci where rhythmic = '水调歌头' and author='苏轼';`

在这里有静夜思, https://github.com/jackeyGao/chinese-poetry/blob/master/json/poet.tang.8000.json#L2531。

[我们所学习的古诗可能是假的.](http://culture.china.com/zh_cn/history/yeshi/11036692/20090201/15302636.html)

**Comment by oldyellowcat** [comment]
谢谢， ... 果然没有找对，我一直在 json 文件里找宋词。。。
